FROM node:12-alpine as build

WORKDIR /usr/src/app
COPY ["package.json", "./"]
RUN yarn
COPY . .
RUN yarn build


FROM nginx:1.21-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


