version: '3.8'

services: 
  db:
    container_name: db
    image: postgres
    environment: 
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    networks:
      - app
  server: 
    container_name: api
    build:
      context: ./Server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    links:
      - db
    networks:
      - app
    command: "yarn run debug"
  client:
    container_name: client
    networks: 
      - app
    env_file:
      - ./.env
    ports:
      - 80:${CLIENT_PORT}
volumes:
  psqldata:
networks:
  app:
    driver: bridge

